<<<<<<< HEAD
theme: jekyll-theme-minimal
title: The title of your site
description: A short description of your site's purpose
show_downloads: "true"
=======
theme: jekyll-theme-cayman
>>>>>>> bc9f4fd508222e8c68d11cf23ec4fc3a933396c6
